### ISSUE TITLE
Running tests from Android Studio does not generate full png image. 

### ISSUE THREAD

**Issue by sanginovs** [Karumi/Shot#134]
Hi,
First of all, thanks for this great library. 

Here's my problem. 
Instead of running gradle task command on a terminal, I run my Shot tests by clicking on run icon from Android Studio: 
<img width="514" alt="Screen Shot 2020-08-27 at 11 10 03 AM" src="https://user-images.githubusercontent.com/16856287/91479138-ddd7e800-e855-11ea-888a-d1d5987d7922.png">
Under the hood, it simply runs adb command to execute test:
```08/27 10:57:14: Launching 'RowScreenshotTest (1)' on Pixel 3a API 29.
Running tests

$ adb shell am instrument -w -r    -e debug false -e class 'com.nextdoor.sampleapp.SampleScreenshotTest' com.sampleapp.debug.test/com.karumi.shot.ShotTestRunner

Connected to process 29576 on device 'Pixel_3a_API_29 [emulator-5554]'.
```

Now, when i run `./gradlew <project><flavor>DownloadScreenshots` in the terminal, it downloads all the images from emulator. However, the images are split into parts and there's not a single full png image. all these images are downloaded into screenshots-default/ folder:
<img width="230" alt="Screen Shot 2020-08-27 at 11 16 42 AM" src="https://user-images.githubusercontent.com/16856287/91479752-cb11e300-e856-11ea-8ccf-92e4363a4bbc.png">

### Expected behaviour
The library should generate full png screenshots instead of generating separate `cut into pieces` screenshot png files.

### Actual behaviour
generating separate `cut into pieces` screenshot files.

### Steps to reproduce
Write a simple test and run using Android Studio run icon instead of running gradle task in the terminal. 
```
 @Test
    fun doScreenshot() {
        // Create view
        val context = InstrumentationRegistry.getInstrumentation().targetContext
        val view: View = LayoutInflater.from(context).inflate(R.layout.some_layout, null, false)
        compareScreenshot(view)
```

### Version of the library
`4.4.0`

The library indeed generates full `png` screenshot files if we run `./gradlew <project><flavor>ExecuteScreenShotTests` in the terminal. However, i am trying to run these tests on Firebase Test Lab and i can't run gradle commands there.

**Comment by pedrovgs** [comment]
Hi @sanginovs! I'm afraid the project has a limitation related to the Gradle plugin execution. As the screenshots have to be downloaded and compared from the Gradle plugin code, we need the Gradle plugin to be able to know if the screenshots are correct or not. That's why you can run the tests from Android Studio with the default configuration, but this will not check if the screenshots are correct or not. 

However, there are two possible solutions you can use:

1. Keep running your tests from Android Studio, but edit your Run/Debug configurations to execute a custom Gradle tasks already declared in Shot. You can configure your IDE to execute something like this:

./gradlew debugExecuteScreenshotTests -Precord -Pandroid.testInstrumentationRunnerArguments.class=com.a.b.MyActivityTest 

or 

./gradlew debugExecuteScreenshotTests -Precord -Pandroid.testInstrumentationRunnerArguments.class=com.a.b.MyActivityTest#MyTestName

This will force the Gradle plugin execution.

2. As you can read in the documentation, you can skip the instrumentation tests execution using this Shot config param:

![Screenshot 2020-09-04 at 08 23 53](https://user-images.githubusercontent.com/4030704/92206915-96221380-ee88-11ea-8ab2-8ca1d454fc5c.png)

This will let you execute the main shot task ./gradlew executeScreenshotTests without executing your tests but downloading and comparing your screenshots.


BTW, the images you mentioned split into parts is the expected behavior as part of the download screenshots task. With the task you executed, the screenshots taken and all the metadata of these screenshots are downloaded from your device to your computer. The format used splits the screenshot into different pieces as a performance improvement. This task is available in case you need to do something special, but as you can see in the task description if you execute ./gradlew tasks

![Screenshot 2020-09-04 at 08 30 55](https://user-images.githubusercontent.com/4030704/92207100-f87b1400-ee88-11ea-94c9-10de316aa8ef.png)

It will not compare the screenshots. This task, as the name describes, will only download the images.

I'm closing this issue now that we have two different solutions 😃 Feel free to reopen it in case you face any other issue.

**Comment by sanginovs** [comment]
Thanks a lot @pedrovgs.
