### ISSUE TITLE
The application UI has been modified error when verifying even though images look identical

### ISSUE THREAD

**Issue by sanginovs** [Karumi/Shot#181]
Hi @pedrovgs 
Thanks so much for your help. I am trying to verify firebase test lab screenshots against baseline screenshot (taken using local emulator). Out of 2 tests, one of them succeeds. However, the first one throwing `The application UI has been modified.` error. If you look at these screenshots, they look identical.
![Screen Shot 2020-12-15 at 1 50 54 PM](https://user-images.githubusercontent.com/16856287/102277028-8e88f680-3edc-11eb-99e2-c8e26c1603db.png)
![Screen Shot 2020-12-15 at 1 52 54 PM](https://user-images.githubusercontent.com/16856287/102277247-d740af80-3edc-11eb-8f1d-9580164e9118.png)
![Screen Shot 2020-12-15 at 1 53 38 PM](https://user-images.githubusercontent.com/16856287/102277314-f0e1f700-3edc-11eb-9713-1bf7d36770a4.png)

I looked at the comparison source code of Shot library in `ScreenshotsComparator` file. 

```
if (!haveSameDimensions(newScreenshot, oldScreenshot)) {
        val originalDimension =
          Dimension(oldScreenshot.width, oldScreenshot.height)
        val newDimension = Dimension(newScreenshot.width, newScreenshot.height)
        Some(
          DifferentImageDimensions(screenshot,
                                   originalDimension,
                                   newDimension))
      } else if (newScreenshot != oldScreenshot) {    // <- hitting this line then throws DifferentScreenshots error
        Some(DifferentScreenshots(screenshot))
      } else {
        None
      } 
```

### Expected behaviour
verification should succeed in the first image as well.

**Comment by pedrovgs** [comment]
Hey @sanginovs could you please upload the two images shot thinks are different? You can find them in ``build/reports/shot``

**Comment by VysotskiVadim** [comment]
@sanginovs, even a few different pixels can cause failed screenshot tests. The human's eye doesn't see the difference, but it's present. Try to compare images from `build/reports/shot` using [online comparator](https://online-image-comparison.com/)(with fuzz 0) and you will see those pixels. I met this tiny difference when I made screenshots on the same emulator using different PCs, one with AMD CPU and the other with Intel. See an example where the difference is highlighted in red: 
![image](https://user-images.githubusercontent.com/6190346/105573449-bdfa1100-5d6e-11eb-8f9d-aa49c451b1e4.png)

@xiphirx [suggests always use the same environment for screenshot tests](https://github.com/facebook/screenshot-tests-for-android/issues/139#issuecomment-353485573). But shot supports [tolerance](https://github.com/facebook/screenshot-tests-for-android/issues/139#issuecomment-353485573), you can try it if your issue is related to environment-specific rendering.

**Comment by sanginovs** [comment]
@pedrovgs here we go:

record image: 
![com nextdoor blocks rows RowScreenshotTest_testRow](https://user-images.githubusercontent.com/16856287/105745398-10643a80-5ef3-11eb-872e-141ffe6c0c28.png)

verify image: 
![com nextdoor blocks rows RowScreenshotTest_testRow](https://user-images.githubusercontent.com/16856287/105745465-296ceb80-5ef3-11eb-8591-7b5f44460a82.png)

**Comment by sanginovs** [comment]
@VysotskiVadim yes i just tried comparing them using online comparator. here's what i got:
the red dots around letters is the differences according to this website:

<img width="1067" alt="Screen Shot 2021-01-25 at 9 57 41 AM" src="https://user-images.githubusercontent.com/16856287/105746014-c465c580-5ef3-11eb-935f-cba59a6115c6.png">

**Comment by sanginovs** [comment]
@pedrovgs @VysotskiVadim i tried running the test with tolerance set at 0.6% and it passed:
![Screen Shot 2021-01-25 at 10 41 53 AM](https://user-images.githubusercontent.com/16856287/105750713-f11cdb80-5ef9-11eb-9eba-39f9e700852c.png)

**Comment by pedrovgs** [comment]
I'm afraid there is nothing else we can do if you are using compose but adding tolerance to your build. The code taking the screenshot fully depends on the hardware profile your device has and this is the main consequence. We've already reported this to the compose team and there is nothing we can do for now. I'm closing the issue.
