### ISSUE TITLE
Why tests running in android studio shows always success?

### ISSUE THREAD

**Issue by felipecastilhos** [Karumi/Shot#185]
### Expected behaviour
The tests should fail when there is a diff on the screenshot

### Actual behaviour
Tests that have a diff in their screenshot are reporting as success.

### Steps to reproduce
- Clone this repo: https://github.com/felipecastilhos/compose-test-sample 
- Change the branch to: `bug/fail-tests`
- The repository already has the shot plugin configured
- The repository has a different screenshot than the actual screen
- Run the tests inside the IDE to see the tests passing
- Run `./gradlew debugExecuteScreenshotTests` and the tests will fail

### Version of the library
Shot 5.5.0

**Comment by pedrovgs** [comment]
Hey @felipecastilhos I'm afraid if you want to run your tests from Android Studio you'll have to configure it to run a gradle task. Shot is a Gradle plugin and it does not integrate with AS as simple as tapping on a button. That's why the README file explains how to run these tests from a terminal. However, if you want to run your tests from AS you can create a configuration like this and it will work:

![Screenshot 2021-01-22 at 08 54 36](https://user-images.githubusercontent.com/4030704/105462815-7badd280-5c8f-11eb-8125-ec3b2d6862c8.png)

I'm sending a PR to explain this as part of the README.

**Comment by felipecastilhos** [comment]
Hey @pedrovgs thanks for always having an amazing support in this lib.
