### ISSUE TITLE
OnlyFailing: still uploads all images

### ISSUE THREAD

**Issue by tobiasKaminsky** [Karumi/Shot#195]
### Expected behaviour
When onlyFailing is set to true, it should only create a report with those images

### Actual behaviour
All recorded images are copied

### Steps to reproduce
- set onlyFailing = true
- let a test fail
- look in recorded folder and see *all* recorded images

### Version of the library
5.8.0

I am not sure, but I guess we have to change
https://github.com/Karumi/Shot/blob/89986deff32a0cd0571bf6df1d848917ea6b2ee2/core/src/main/scala/com/karumi/shot/screenshots/ScreenshotsSaver.scala#L32-L41

@pedrovgs if you can verify this, I will create a PR

**Comment by tobiasKaminsky** [comment]
Tried to use shot-consumer for testing, but it requires 4.3. 
As this is not yet stable, I cannot use it.

So I can only create an untested PR.

**Comment by pedrovgs** [comment]
Hey @tobiasKaminsky you are absolutely right. All the images and the metadata are copied. We would need to add an extra step to remove the images. We need to download them all from the device in order to know how many of them are wrong or not..we could remove them after analyzing the metadata file and comparing all the images, but I'm not sure if this is worth it. Could you please tell me why this is an issue for you?

**Comment by pedrovgs** [comment]
Ahhh I see, you mean the report folder!!! I'm going to take a look at your PR. I guess you are saving the reports and the lower the size the better.

**Comment by pedrovgs** [comment]
Fixed!! Thank you so much @tobiasKaminsky 😃
