### ISSUE TITLE
Feature Request: Only start a single test for recording

### ISSUE THREAD

**Issue by sockeqwe** [Karumi/Shot#31]
I might be overlooking something, but is it possible to only run the "recording" mode for one single layout?

Example where this feature would be useful:
Let's say you have to change a xml layout `foo.xml` i.e. change the `padding-top` value which actually uses a `dimen` defined under `@dimen/padding_top`.
If some other layout like `bar.xml` also uses`@dimen/padding_top` which you are not aware of, `bar.xml` layout will also look different suddenly. However, if you re-record all screenshots then you will miss the changes on `bar.xml` because not only the screenshot for `foo.xml` has been re-recoreded, but also the screenshot of `bar.xml` (which means the "visual error" in `bar.xml` is not detected)

**Comment by pedrovgs** [comment]
This shouldn't be so hard to implement. I think the official Facebook library does not support it but we could do it. We could use the [Android Official documentation](https://developer.android.com/studio/test/command-line.html) about "Tests from command line". 

There are just two things to take into account:

* The public param configured in ``ShotExtension`` should be similar to the one used in ADB to execute just one test.
* If just one test is executed just one test should be recorded or verified 😃 

@sockeqwe this issue is on our roadmap since the very beginning but I completely forgot to create the issue. If you'd like to contribute to our project with this feature it could be awesome 😃 I think this task is simple enough for a first contribution.

**Comment by sockeqwe** [comment]
yep, I'm trying to dedicate some time for it next week. Thanks for your quick response!

**Comment by pedrovgs** [comment]
Great thanks! Let me know if you need something 😃

**Comment by Serchinastico** [comment]
Hi,

I got it working by running the following command:

```
./gradlew executeScreenshotTests -Precord -Pandroid.testInstrumentationRunnerArguments.class=com.your.package.YourClassTest
```

You can even run a single test with

```
./gradlew executeScreenshotTests -Precord -Pandroid.testInstrumentationRunnerArguments.class=com.your.package.YourClassTest#yourTest
```

I'm updating the project README in https://github.com/Karumi/Shot/pull/39.

**Comment by pedrovgs** [comment]
@sockeqwe @Serchinastico feature implemented just by updating the documentation!! \o/
