### ISSUE TITLE
Running multiple tests using Espresso.

### ISSUE THREAD

**Issue by ohmygar** [Karumi/Shot#44]
I am combing the espresso with Karumi shot. It generates the report successfully for 2 tests if they fail the comparison. However, if the espresso cannot find some element for 1 test and fail at some point. The report won't be generated at all. 
Thus I am not able to know any information, any ideas how to fix this? 
Thanks

**Comment by pedrovgs** [comment]
Hi @ohmygar. Espresso does not generate the report if the test fails because of how the plugin is implemented. Unfortunately, we won't be able to change this implementation for now.

If the report is not generated is because you have an Espresso test with a crash or an ``onView`` or ``assertX`` failing. Review your tests, debug them and you'll find the error.

I hope this answers your question. Feel free to open this issue again if you have any other issue.
