### ISSUE TITLE
FileNotFoundException for metdata.xml file while running a particular case

### ISSUE THREAD

**Issue by arjungovindgv** [Karumi/Shot#55]
Expection Got :
java.io.FileNotFoundException: /Users/...../app/screenshots/screenshots-default/metadata.xml (No such file or directory)

Command Run : ./gradlew executeScreenshotTests -Pandroid.testInstrumentationRunnerArguments.class=testcases.Test0AppLaunch -Precord

Am I did any mistake ?
 while running for the whole test suite its working fine.

**Comment by Serchinastico** [comment]
Hi @arjungovindgv 

I think I had this very same problem when the emulator didn't have write permissions for the sdcard or there was a major problem running tests (some sort of crash). Try deleting and creating the emulator again and see how it goes. Another thing to watch here is the facebook's dependency version.

You can find a working project here: https://github.com/Karumi/KataScreenshotKotlin. Try cloning the repo and executing `./gradlew executeScreenshotTests -Precord` to see if it's a problem with the emulator or the library.

**Comment by arjungovindgv** [comment]
@Serchinastico If its a permission issue ? then how the entire test suite will run but not its very first class.
I tried with Real Device too.. got the same problem


Thanks for the immediate Reply

**Comment by Serchinastico** [comment]
I meant write permissions as in the file system permissions, not in the AndroidManifest declaration way. Anyways it was just a wild guess as I'm lacking some context here. If I'm understanding your problem right it's that running a single test class fails with the "no such file..." error message, isn't it? Are you sure you are running the command with the whole package name + class name? As in

`./gradlew clean executeScreenshotTests -Pandroid.testInstrumentationRunnerArguments.class=com.karumi.ui.view.MainActivityTest`

Try running that on the sample project (https://github.com/Karumi/KataScreenshotKotlin) and see if it works. Once you run it we will know if the issue is in the emulator, in your project's configuration or the library itself.

**Comment by arjungovindgv** [comment]
Hi @Serchinastico 

Sample Project working fine. Even for my project test is running perfectly getting error in report generation part alone that too on running a particular class or method 

Logcat trace : 


 Task :app:downloadScreenshots
??  Pulling screenshots from your connected device!

> Task :app:executeScreenshotTests FAILED
?  Comparing screenshots with previous ones.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:executeScreenshotTests'.
> java.io.FileNotFoundException: /Users/..../app/screenshots/screenshots-default/metadata.xml (No such file or directory)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.1/userguide/command_line_interface.html#sec:command_line_warnings

**Comment by Serchinastico** [comment]
If the project I linked you is working try comparing its dependencies and project configuration. More specifically, see if there is any difference in the `'com.facebook.testing.screenshot:core'` version. Apart from that, I'm kind of lost here without more context. Can you send us a minimal project where the lib is not working so that we can see what's happening?

**Comment by arjungovindgv** [comment]
@Serchinastico can you share you mail ID where I can send those fails in private for detail ?

**Comment by Serchinastico** [comment]
I'm afraid not, we try to offer support for the library, not your specific project. If you can create an open source minimal project replicating the issue we will be glad to help you and it will be way easier for us to spot the issue.

**Comment by arjungovindgv** [comment]
I am having a test class under 
/app/src/androidTest/java/testcases/TestClass


Build Gradle File Dependency

 androidTestImplementation 'com.android.support.test.uiautomator:uiautomator-v18:2.1.3'
//    androidTestImplementation 'com.android.support:support-annotations:28.0.0'
    androidTestImplementation 'com.android.support.test.espresso:espresso-web:3.0.2'
    androidTestImplementation 'com.android.support.test:rules:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-idling-resource:3.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-contrib:3.0.0'
    androidTestImplementation 'org.assertj:assertj-core:2.0.0'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'

    //spoon - report generator - automations
    androidTestImplementation 'com.squareup.spoon:spoon-client:1.6.4'


//    facebook
    androidTestImplementation('com.facebook.testing.screenshot:core:0.4.2') {
        exclude group: 'com.crittercism.dexmaker', module: 'dexmaker'
        exclude group: 'com.crittercism.dexmaker', module: 'dexmaker-dx'
    }
 
}
shot {
    appId = "***app Id****'
    instrumentationTestTask = 'connectedPhoneDebugLocalAndroidTest'
    packageTestApkTask = 'packagePhoneDebugLocalAndroidTest'

}
spoon{
    singleInstrumentationCall = true
}


On running this command

./gradlew executeScreenshotTests -Pandroid.testInstrumentationRunnerArguments.class=testcases.TesClass -Precord


test is running fine and everthing works fine but for report generation I am getting 

Task :app:downloadScreenshots
?? Pulling screenshots from your connected device!
Task :app:executeScreenshotTests FAILED
? Comparing screenshots with previous ones.
FAILURE: Build failed with an exception.
What went wrong:
Execution failed for task ':app:executeScreenshotTests'.
java.io.FileNotFoundException: /Users/..../app/screenshots/screenshots-default/metadata.xml (No such file or directory)
Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
Get more help at https://help.gradle.org
Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.1/userguide/command_line_interface.html#sec:command_line_warnings

**Comment by arjungovindgv** [comment]
what more info you are expecting me to provide ? If I run the whole test suite its working fine but getting while running a particular class or method

**Comment by arjungovindgv** [comment]
@Serchinastico any update on this

**Comment by pedrovgs** [comment]
@arjungovindgv why are you using ``androidTestImplementation('com.facebook.testing.screenshot:core:0.4.2')``? This might be the issue. Could you try removing this dependency?

On the other hand, could you check the test you are executing passes just running it from Android Studio? If the issue is not related to the lib version it has to be related with how the library is saving the screenshots and we'd need to know if the test pass from Android Studio.

**Comment by arjungovindgv** [comment]
Finally after removing the dependency, it got worked.
Thank you so much @pedrovgs @Serchinastico

**Comment by pedrovgs** [comment]
You are welcome @arjungovindgv Thanks for using shot, we love seeing people writing tests!!!
