### ISSUE TITLE
Application suffix ID declared in build type not being handled properly

### ISSUE THREAD

**Issue by mandomi** [Karumi/Shot#79]
I've created a simple project and Shot works perfectly when there isn't any flavor but when I add flavors I would get this error:

`> Task :app:downloadScreenshots FAILED
⬇️  Pulling screenshots from your connected devices!

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:downloadScreenshots'.
> Nonzero exit value: 1
`

I've also added this to the gradle file:

`shot {
    appId = 'com.example.snapshottesting'
    instrumentationTestTask = 'connectedDevDebugAndroidTest'
}
`

**Comment by mandomi** [comment]
I have found the answer!
I've added `applicationIdSuffix ".dev"` to the Dev flavor, so the application id in the Dev is not the same as production.
So, I had to change the appid to `appId = 'com.example.snapshottesting.dev'.

I suggest adding the capability of working Shot with different environments.

**Comment by scm573** [comment]
Hey guys!

I meet the same trouble after upgraded to 4.0.0, because the "appId" configuration is gone now.
Is there any way to deal with this?

**Comment by mandomi** [comment]
@scm573 I upgraded to 4.0.0 too, you don't need to use the appId anymore. It works for me.

**Comment by scm573** [comment]
@mandomi 

I tried many different patterns and probably found the root cause.
Where we put "applicationIdSuffix" is not in the productFlavors block, but the buildTypes block.
And due to this process
https://github.com/Karumi/Shot/blob/master/shot/src/main/scala/com/karumi/shot/ShotPlugin.scala#L68
The applicationIdSuffix declared in buildTypes block is not being taken into consideration.

Also that's why, it works fine if I remove that applicationIdSuffix declaration, or downgrading to v3.1.0 to use the appId declaration explicitly.

**Comment by pedrovgs** [comment]
Thanks for the info @scm573 I'm going to see If I can fix it.

**Comment by pedrovgs** [comment]
The fix will be available in the next release I'm about to publish
