### ISSUE TITLE
How to make snapshot of full screen with real backend data

### ISSUE THREAD

**Issue by slacklab** [Karumi/Shot#93]
Hello, can you help me:

I want make snapshot tests by this principle:

1. Open my application with real backend
2. Make first snapshot of full screen (with data from backend)
3. Go to different screen by tap the some button
4. Make second snapshot of full screen else
5. And so on, click to different screens and make comparsion of snapshots

Cannot understand how to make full snapshot of screen (for comparsion)
Only I can make snapshot of view - it is looks like layout at AS (without any data from my backend)
Or can make snapshot of activity (without backend data yet)
Tell me pls, how i can make snapshot of full screen with Karumi/Shot?

I cannot find out how to do this. 
Maybe any examples of code. 

### Steps to reproduce
I use this code for make snapshot without real data
```
val context = getInstrumentation().targetContext
                context.setTheme(com.kg.gettransfer.R.style.AppTheme)
                val inflater = LayoutInflater.from(context)
                val view = inflater.inflate(com.google.android.material.R.layout.design_bottom_sheet_dialog, null, false)
                ViewHelpers.setupView(view).setExactWidthDp(500).setExactHeightDp(700).layout()
                Screenshot.snap(view).record()


```

### Version of the library
3.0.2

**Comment by digitalbuddha** [comment]
Warning: This might be a bit hacky but it works consistently for me

 
 ``` 
public static Activity getCurrentActivity() {
        waitUntilIdle();

        final Activity[] activity = new Activity[1];
        getInstrumentation()
                .runOnMainSync(
                        new Runnable() {
                            @Override
                            public void run() {
                                Collection<Activity> activities =
                                        ActivityLifecycleMonitorRegistry.getInstance()
                                                .getActivitiesInStage(Stage.RESUMED);
                                activity[0] = Iterables.getOnlyElement(activities);
                            }
                        });
        return activity[0];
    }
```

Next make a global/ top level counter for number of screenshots taken since each one has to have a different "name"
`    val screenshotCount = AtomicInteger(0)`

finally make a global function that you can call from anywhere
```
fun verify(){
 Screenshot.snapActivity(UiTestUtils.getCurrentActivity()).setName(screenshotCount.incrementAndGet().toString()).record();
}
```

Call `verify` from anywhere in a test and each time it should snap the entire screen

**Comment by slacklab** [comment]
Thanks a lot for help
It was very usefull info for us

Now i can make snapshot of current activity - it works very nice!

But now i only can make snapshot of activity (without framelayout at top of activity)

Maybe you can help me please, how i can make snapshot for all views: activity and framelayout at top of activity?

Cos i have screen with modal bottom sheet window at top my screen (activity)

**Comment by pedrovgs** [comment]
@slacklab some views like the one you shown in a dialog have to been recorded using a different call. However, your questions are not related to this gradle plugin but about testing in general, so I'm closing the issue for now. My recommendation is to ask your question in StackOverflow, because there are some libraries and techniques involved at the same time. You can also take a look at this blog post I wrote years ago https://blog.karumi.com/world-class-testing-development-pipeline-for-android-part-4/ and at these katas:

https://github.com/Karumi/KataScreenshotKotlin/
https://github.com/Karumi/katasuperheroeskotlin

where you can review how to test all the different scenarios of your application. The main difference is you will not point the app to the real API but I think this approach will be better for you if you want to use screenshot testing.
